/* eslint-disable no-undef */
module.exports = {
  content: [],
  theme: {
    spacing: {
      '4': '.25rem',
      '8': '.5rem',
      '16': '1rem',
      '24': '1.5rem',
      '32': '2rem',
      '40': '2.5rem',
      '48': '3rem',
      '56': '3.5rem',
      '64': '4rem',
      '72': '4.5rem',
      '80': '5rem',
      '96': '6rem',
      '104': '6.5rem',
      '112': '7rem',
      '120': '7.5rem',
      '160': '10rem',
      '200': '12.5rem',
      '320': '20rem',
      '720': '45rem',
      '1024': '64rem',
      '1200': '75rem',
      '1920': '120rem',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      'neutral-dark': { pure: '#000000', '01': '#737479', '02': '#5f646d', '03': '#303236' },
      'neutral-light': { pure: '#ffffff', '01': '#f8f9fa', '02': '#f0f0f0', '03': '#e4e5e7' },
      alert: { pure: '#e6b319', '01': '#faf1d7', '02': '#f0d275', '03': '#896804' },
      danger: { pure: '#fc5346', '01': '#ffece9', '02': '#ffa4a2', '03': '#d10f1c' },
      informative: { pure: '#c9cbce', '01': '#e4e5e7', '02': '#494b50', '03': '#303236' },
      positive: { pure: '#30c05b', '01': '#e1ffea', '02': '#8ae8a6', '03': '#087c2b' },
      primary: { pure: '#1E5BC6', '01': '#e0ecff', '02': '#70a5ff', '03': '#002c7a' },
      secondary: { pure: '#ba007c', '01': '#ffd2f0', '02': '#ff79b4', '03': '#840058' },
      highlight: { pure: '#e6007e', '01': '#ffd2f0', '02': '#ff79b4', '03': '#840058' },
      graphic: { '01': '#1bafe6', '02': '#b0c0fc', '03': '#002199', '04': '#18191b', '05': '#18191b' },
    },
    fontFamily: {
      base: ['proxima-nova', 'sans-serif' ],
    },
    fontWeight: {
      regular: 400,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      default: '100%',
      tiny: '120%',
      distant: '150%',
    },
    fontSize: {
      xxs: '.875rem',
      xs: '1rem',
      sm: '1.25rem',
      md: '1.5rem',
      lg: '2rem',
      xl: '2.5rem',
    },
    borderRadius: {
      none: '0',
      sm: '.125rem',
      md: '.25rem',
      lg: '.5rem',
      pill: '9999px',
    },
    borderWidth: {
      none: '0',
      hairline: '.125rem',
      thin: '.1875',
      thick: '.25rem',
      heavy: '.5rem',
    },
    opacity: {
      'level-light': '.16',
      'level-medium': '.32',
      'level-semiintense': '.48',
      'level-intense': '.64',
      'level-semiopaque': '.8',
    },
    boxShadow: {
      'level-1': '0 -0.0625rem .5rem 0 rgba(0, 0, 0, .08), 0 .125rem .125rem 0 rgba(0, 0, 0, .16)',
      'level-2': '0 -0.0625rem .5rem 0 rgba(0, 0, 0, .08)',
    },
    screens: ({ theme }) => ({
      'phone': theme('spacing.320'),
      'portrait-tablet': theme('spacing.720'),
      'landscape-tablet': theme('spacing.1024'),
      'desktop': theme('spacing.1200'),
      'big-desktop': theme('spacing.1920'),
    }),
    container: ({ theme }) => ({
      'phone': theme('screens.phone'),
      'portrait-tablet': theme('screens.portrait-tablet'),
      'landscape-tablet': theme('screens.landscape-tablet'),
      'desktop': theme('screens.desktop'),
      'big-desktop': theme('screens.big-desktop'),
      center: true,
      padding: {
        DEFAULT: theme('spacing.32'),
        sm: theme('spacing.16'),
        md: theme('spacing.32'),
        lg: theme('spacing.56'),
        xl: theme('spacing.112'),
        '2xl': theme('spacing.160'),
      },
    }),
    extend: {
      'spacing-stack': ({ theme }) => ({
        'quark': theme('spacing.4'),
        'nano': theme('spacing.8'),
        'xxxs': theme('spacing.16'),
        'xxs': theme('spacing.24'),
        'xs': theme('spacing.32'),
        'sm': theme('spacing.40'),
        'md': theme('spacing.48'),
        'lg': theme('spacing.56'),
        'xl': theme('spacing.64'),
        'xxl': theme('spacing.80'),
        'xxxl': theme('spacing.120'),
        'huge': theme('spacing.160'),
        'giant': theme('spacing.200'),
      }),
      'spacing-inline': ({ theme }) => ({
        'quark': theme('spacing.4'),
        'nano': theme('spacing.8'),
        'xxxs': theme('spacing.16'),
        'xxs': theme('spacing.24'),
        'xs': theme('spacing.32'),
        'sm': theme('spacing.40'),
        'md': theme('spacing.48'),
        'lg': theme('spacing.64'),
        'xl': theme('spacing.80'),
      }),
      'spacing-inset': ({ theme }) => ({
        'quark': theme('spacing.4'),
        'nano': theme('spacing.8'),
        'xs': theme('spacing.16'),
        'sm': theme('spacing.24'),
        'md': theme('spacing.32'),
        'lg': theme('spacing.40'),
      }),
      'spacing-squish': ({ theme }) => ({
        'quark': theme('spacing.4') + ' ' + theme('spacing.8'),
        'nano': theme('spacing.8') + ' ' + theme('spacing.16'),
      }),
      'gutter':({ theme }) => ({
        '16': theme('spacing.16'),
        '32': theme('spacing.32'),
        '112': theme('spacing.112'),
        '160': theme('spacing.160'),
      }),
      'breakpoint':({ theme }) => ({
        'phone': theme('screens.phone'),
        'portrait-tablet': theme('screens.portrait-tablet'),
        'landscape-tablet': theme('screens.landscape-tablet'),
        'desktop': theme('screens.desktop'),
        'big-desktop': theme('screens.big-desktop'),
      }),
      flexbox: {
        'wrap': 'wrap',
        'row': 'row', 
        'flex': 'flex', 
        'row-reverse': 'row-reverse', 
        'column-reverse': 'column-reverse', 
        'flex-start': 'flex-start', 
        'center': 'center', 
        'start': 'start',
        'space-around': 'space-around',
        'space-between': 'space-between',
      },
      'shadow': ({ theme }) => ({
        'level-1': theme('boxShadow.level-1'),
        'level-2': theme('boxShadow.level-2'),
      }),
    },
  },
  variants: {
    gradients: ['responsive', 'hover'],
  },
  plugins: [
  ]
}